### ISSUE TITLE
Rogue device's SWINT interface MAC leaking

### ISSUE THREAD

**Issue by grmpyninja** [scipag/nac_bypass#3]
Is there a way to prevent leaking MAC address of the network interface connected to the switch when in interactive mode  (after connection setup). While injecting packets from the rogue device via bridge I can perfectly hit the internal network, but apparently my MAC address is leaking and I can see it on my router's sniffer. When victim sends packets everything works fine as it goes through the bridge and it is completely transparent and there is no indicator that there is a man in the middle, but when I want to interact with the network from the bridge I can be easily detected in the network (e.g. MAC whitelists).

**Comment by 0x6d69636b** [comment]
That's odd. Can you provide us with the full output of the script when you initially run it? What operating system are you using as the attack machine?

**Comment by grmpyninja** [comment]
it's newest kali on raspberry pi4. I expected every packet sent on kali which uses the bridge as a default gateway should go through the ebtables rule and get the correct victim's mac. Instead wheb i sniff the traffic on my mikrotik i got my br0' mac. br0 should not be set to victim's right? as it would simply break the L2 routing. im wondering if there is something that make ebtable not work as expected.

**Comment by 0x6d69636b** [comment]
Can you check after running the script if all ebtables rules are set correctly: `ebtables -L`? Which version of ebtables is used in your Kali version?

**Comment by grmpyninja** [comment]
both rules are there in postrouting (i launched basic init and -c without responder). I experimented with both rpi3b and rpi4. on rpi3b i got ebtables legacy (2.0.11) as it was strikedout in readme, and on rpi4 it's 1.8.6 nf_tables, but both behave the same, and while pinging from raspberry the network i got my rpi adapters mac in frames in sniffer

**Comment by grmpyninja** [comment]
Made it work on rpi4. Apparently incorrectly i wanted to do it in two stages. First launch transparent bridge so only phase1. Then after sniffing stuff I wanted to invoke only the phase two (connection/interactive). And it looks like it doesn't work that way. However when i invoke init only, then reset whole and then I invoke the whole script again with both phases at the same time it works fine and I can't see my rpi adapter mac. I'm not using awareness script and tcpdump kerberos as I wanted to manually sniff the traffic for a while (for printer setup), adjust victim and gw mac adresses, then set static and then switch to full interactive mode manually. that's why i did it in phases, but it apparently doesn't work. maybe it's due to some missing bridge interface reset/flish at some point. will debug it later. I got to check same flow on rpi3b i got.

**Comment by 0x6d69636b** [comment]
Oh, then it's clear. During the first stage you may only be passive, otherwise information leaks into the network. Only after the second stage is complete can you start activities with your attacker system, as only then is the MAC address disguised.

The split into several phases was the basis for the awareness script. Our thought was that attackers drop the device in a meeting room and no device is connected for a while. Then the device remains in phase 1 until it records new network traffic again and can pretend to be a new device.

**Comment by grmpyninja** [comment]
yea I assumed it was the case, that's why i used it first with phase 1 only and then after i sniffed some stuff i manually invoked phase2. but apparently i got to do it the way it is passive, then sniff stuff, set params manually. then -r to reset everything and start again both phases. If I'm simply in the passive phase and then I invoke the script with phase2 only to configure remaining ebtables rules then my mac leaks. However when I'm in passive, then I do -r to reset stuff and then invoke again both phases it works. so maybe i simply broke it when i did it manually. I'll debug this case to figure out what was wrong and whether it was my mystake or some missing interface flush.

**Comment by grmpyninja** [comment]
in the end rpi4 with newest kali works fine and rpi3b is broken and still leaks that MAC. apparently when i check ebtables after starting a script (both phases) as it should work and worked for rpi4 i end up with ebtables rules added in both ebtables-nft and ebtables-legacy.

**Comment by 0x6d69636b** [comment]
Is there anything we can adjust in the script to solve the problem? Otherwise, I would close the issue.

**Comment by grmpyninja** [comment]
let's close it for now as it works on one device and doesn't work on the other one, but I will get that not working one back next week and so I can do more testing.
