### ISSUE TITLE
SIOCSMIREG on eth0: Operation not supported

### ISSUE THREAD

**Issue by Netskeepy** [scipag/nac_bypass#4]
Hey, after configuring as your description, run the script and then put the cables as well,
I got this error:
SIOCSMIREG on eth0: Operation not supported

**Comment by 0x6d69636b** [comment]
That could be an error message from the mii-tool. What is your setup like? Do you use virtualisation? If so, are you using VMware or HyperV? I guess the network adapter is not fully supported, that is for example the case when using Hyper-V...

**Comment by Netskeepy** [comment]
My setup is:
Physical Kali Machine with 2 NIC. (eth0-onboard, eth1-USB Ethernal adapter)
the eth0 is my physical network card.
I will try to plug USB Ethernet adapter instead of my onboard card.

**Comment by 0x6d69636b** [comment]
You can simply run `mii-tool <interface>` to see if the network card is fully supported. If you have two identical USB Ethernet adapters it should work :crossed_fingers:

**Comment by Netskeepy** [comment]
> 

The command only checks the network connection status, not really helpful...

**Comment by 0x6d69636b** [comment]
In this case, yes. But we use this tool to reset the connection during the bypass script. If you get any errors by running the commands, like some operations are not supported, then the bypass script will fail. So this dry run helps to see if your adapters are fully functional.

**Comment by 0x6d69636b** [comment]
I replaced mii-tool with ethtool, it might work now ;-)
